# Generated by Django 5.2.14 on 2026-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RenovationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Название проекта"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Имя клиента"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=40, verbose_name="Телефон"),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Площадь, м²",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to="projects/", verbose_name="Файл проекта"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("uploaded", "Загружен"),
                            ("in_review", "На проверке"),
                            ("ready", "Готов к расчёту"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
                ),
            ],
            options={
                "verbose_name": "проект ремонта",
                "verbose_name_plural": "проекты ремонта",
                "ordering": ["-created_at"],
            },
        ),
    ]
