# Generated by Django 5.2.14 on 2026-06-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="project_uploads/", verbose_name="Файл"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Площадь квартиры",
                    ),
                ),
                (
                    "repair_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("economy", "Эконом"),
                            ("standard", "Стандарт"),
                            ("premium", "Премиум"),
                        ],
                        max_length=20,
                        verbose_name="Уровень ремонта",
                    ),
                ),
                (
                    "ai_status",
                    models.CharField(
                        default="demo", max_length=20, verbose_name="AI статус"
                    ),
                ),
                (
                    "ai_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="AI summary"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "загрузка проекта",
                "verbose_name_plural": "загрузки проектов",
                "ordering": ["-created_at"],
            },
        ),
    ]
