# Generated by Django 5.2.14 on 2026-05-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
            ],
            options={
                "verbose_name": "категория услуг",
                "verbose_name_plural": "категории услуг",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ServicePackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=140, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="Слаг")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Краткое описание"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Базовая цена",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="packages",
                        to="marketplace.servicecategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "пакет услуг",
                "verbose_name_plural": "пакеты услуг",
                "ordering": ["title"],
            },
        ),
    ]
