# Generated by Django 5.2.14 on 2026-05-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("area_m2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rooms", models.PositiveSmallIntegerField()),
                (
                    "repair_segment",
                    models.CharField(
                        choices=[
                            ("economy", "Эконом"),
                            ("comfort", "Комфорт"),
                            ("business", "Бизнес"),
                        ],
                        default="comfort",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("calculated", "Рассчитан"),
                            ("submitted", "Отправлен"),
                            ("in_progress", "В работе"),
                            ("done", "Завершен"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Проект клиента",
                "verbose_name_plural": "Проекты клиентов",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculator_slug", models.SlugField(max_length=100)),
                ("area_m2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("rooms", models.PositiveSmallIntegerField()),
                ("thickness", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "segment",
                    models.CharField(
                        choices=[
                            ("economy", "Эконом"),
                            ("comfort", "Комфорт"),
                            ("business", "Бизнес"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "materials_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "works_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("result_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to="accounts.clientproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расчет",
                "verbose_name_plural": "Расчеты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MasterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("specialization", models.CharField(max_length=255)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("description", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="masters/"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль мастера",
                "verbose_name_plural": "Профили мастеров",
            },
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("master", "Мастер"),
                            ("supplier", "Поставщик"),
                            ("full_repair", "Ремонт под ключ"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("viewed", "Просмотрена"),
                            ("responded", "Есть ответ"),
                            ("accepted", "Принята"),
                            ("rejected", "Отклонена"),
                            ("closed", "Закрыта"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "calculation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="accounts.calculation",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to="accounts.clientproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на сервис",
                "verbose_name_plural": "Заявки на сервис",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="MasterResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_from", models.DecimalField(decimal_places=2, max_digits=12)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="accounts.masterprofile",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_responses",
                        to="accounts.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ мастера",
                "verbose_name_plural": "Ответы мастеров",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=255)),
                ("whatsapp", models.CharField(blank=True, max_length=32)),
                ("delivery_info", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль поставщика",
                "verbose_name_plural": "Профили поставщиков",
            },
        ),
        migrations.CreateModel(
            name="SupplierMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=120)),
                ("unit", models.CharField(max_length=30)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("stock_status", models.CharField(max_length=120)),
                ("delivery_time", models.CharField(blank=True, max_length=120)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="accounts.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Материал поставщика",
                "verbose_name_plural": "Материалы поставщиков",
            },
        ),
        migrations.CreateModel(
            name="SupplierResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонен"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_responses",
                        to="accounts.servicerequest",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="accounts.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ поставщика",
                "verbose_name_plural": "Ответы поставщиков",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("client", "Клиент"),
                            ("master", "Мастер"),
                            ("supplier", "Поставщик"),
                            ("admin", "Администратор"),
                        ],
                        default="client",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("city", models.CharField(blank=True, max_length=120)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
                "ordering": ("-created_at",),
            },
        ),
    ]
